// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbOEVvvNwCq68c0pn-q52jVWRQZ0MUjVA',
    appId: '1:238511471890:web:13b3e40bfcb023a68487cb',
    messagingSenderId: '238511471890',
    projectId: 'stovegenie-c825e',
    authDomain: 'stovegenie-c825e.firebaseapp.com',
    storageBucket: 'stovegenie-c825e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCY0YRDMwrt-8-ZOy-6fKrzEyEGhC58Jvk',
    appId: '1:238511471890:android:932b8ef12cc681808487cb',
    messagingSenderId: '238511471890',
    projectId: 'stovegenie-c825e',
    storageBucket: 'stovegenie-c825e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKAVQl7b9p20iHDeA4jDmSKyfeMXtUUoE',
    appId: '1:238511471890:ios:f16fd9a2fae5e3af8487cb',
    messagingSenderId: '238511471890',
    projectId: 'stovegenie-c825e',
    storageBucket: 'stovegenie-c825e.firebasestorage.app',
    iosBundleId: 'com.example.stoveGenie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKAVQl7b9p20iHDeA4jDmSKyfeMXtUUoE',
    appId: '1:238511471890:ios:f16fd9a2fae5e3af8487cb',
    messagingSenderId: '238511471890',
    projectId: 'stovegenie-c825e',
    storageBucket: 'stovegenie-c825e.firebasestorage.app',
    iosBundleId: 'com.example.stoveGenie',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbOEVvvNwCq68c0pn-q52jVWRQZ0MUjVA',
    appId: '1:238511471890:web:673c2dfefb38016a8487cb',
    messagingSenderId: '238511471890',
    projectId: 'stovegenie-c825e',
    authDomain: 'stovegenie-c825e.firebaseapp.com',
    storageBucket: 'stovegenie-c825e.firebasestorage.app',
  );
}
